### PR TITLE
Remove the --unity-launch flag

### PR DESCRIPTION
**Pull request by m3t4f1v3**
See https://github.com/microsoft/vscode/issues/202545

### CODE REVIEW

**Comment by nihaals** [comment]
What do you think about replacing it with `--new-window`? I can't test the differences to see which makes more sense but it sounds like that would maintain the current behaviour.

**Comment by m3t4f1v3** [comment]
On my desktop (KDE plasma 6), it makes a new window if I open it from the launch menu, I imagine this is the intended behavior according to the linked issue.
Using --new-window makes Visual Studio open a new window each time a file is opened, irrespective of the folder the files are placed in.

**Comment by nihaals** [comment]
Ah that makes sense, I didn't think about it being used when launching files too.

**Review by nihaals — APPROVED** [review]

**Comment by nihaals** [comment]
Thanks!

**Pull request merged**
